services:
  web:
    build: .
    container_name: flask-crud-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=server
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - MONGO_URI=mongodb://mongo:27017/Flask-CRUD
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
